In [280]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
import io
import nltk
#nltk.download('stopwords')
import re
plt.show()
from sklearn.feature_extraction.text import *
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from nltk import word_tokenize, sent_tokenize
from nltk.corpus import stopwords
from nltk.stem import LancasterStemmer
from sklearn.preprocessing import *
from numpy import argmax
import warnings
warnings.filterwarnings("ignore")

import os
import nltk
import urllib
from urllib.request import urlopen
from bs4 import BeautifulSoup
from nltk import word_tokenize
import codecs
import pandas as pd

cwd = os.getcwd()
#testing with codecs to open a html file, not necessarily needed though.
import codecs
#data1 = codecs.open('/Users/sidraaziz/PycharmProjects/MLProject/Gutenberg_19th_century_English_Fiction/pg11CarolAlice-content.html','r')
#print(data1.read())

dataset = pd.read_csv(r'/Users/sidraaziz/PycharmProjects/ProjectGutenberg/Gutenberg_Features3.csv', sep=',', engine='python')
dataset.fillna(value = 0, inplace=True)

#Now dataframe created above can be split into Features (X) and Target class (y)
le_target = LabelEncoder()
obj_dataset= dataset.select_dtypes(include=['object']).copy()
obj_dataset.head()
obj_dataset['genre_label'] = le_target.fit_transform(obj_dataset['Target_Class'])

print()
#print('below is the list seperation with Target_Class encoded:')
#print(obj_dataset[['genreLabel', 'Target_Class']])
features = ['p_tag_count','comma_count','colon_count','hyphen_count','TTR','Positive','Neutral','Negative','FleschK_score','CC','PRP','PRP$','IN','NNP','period_count']
# Separating out the features
X = dataset.loc[:, features].values
# Separating out the target
y = obj_dataset.loc[:,['Target_Class']].values

dataset = dataset.drop('Target_Class',axis=1)

#print(len(y.data))

#onehotencoding on above label encoder
onehot_encoder = OneHotEncoder(sparse=False)
#obj_dataset['genre_label'] = obj_dataset['Target_Class'].values.reshape(len(obj_dataset['Target_Class']), 1)
#onehot_encoded = onehot_encoder.fit_transform(obj_dataset['genre_label'].values.reshape(-1,1))
onehot_encoded = onehot_encoder.fit_transform(y.reshape(-1,1))

#print(onehot_encoded)


# invert first example
inverted = le_target.inverse_transform([argmax(onehot_encoded)])
#print (onehot_encoded[20])

y = obj_dataset['genre_label']

#print(y)


# create training and testing sets
X_train, X_test, y_train, y_test = train_test_split(dataset, y, test_size=0.25)
#print('Data for X_train before stopword removal:')
#print(X_train.shape, y_train.shape)
print()
#print(X_test.shape, y_test.shape)

#print(X_train)
print()
#print(y_train)






     p_tag_count  comma_count  colon_count  hyphen_count    TTR  Positive  \
718         5335        13662          296          2045  0.086     0.314   
196         2145         7124           42          2270  0.155     0.178   
482          923         4349          104          1058  0.193     0.228   
590         1557         3367           29           921  0.218     0.188   
898         2701         4811          121          1400  0.212     0.170   
793         2314         6212           24          1209  0.156     0.223   
345          343         4153           39           913  0.181     0.191   
582         1713         7260          111           995  0.185     0.204   
886          180          631           17           139  0.383     0.251   
138         2496         6972           45          1935  0.172     0.254   
913         2913        13821          146          2557  0.103     0.263   
169         1789         6849          118          1689  0.183     0.237 

In [281]:
from sklearn.preprocessing import StandardScaler
standardscaler = StandardScaler()

standardscaler.fit(X_train)
X_train = standardscaler.transform(X_train)
X_test = standardscaler.transform(X_test)

#X_train

array([[ 3.12802531,  1.94396893,  1.3534892 , ...,  1.38533443,
         0.34459564,  1.97659814],
       [ 0.33949875,  0.28922912, -0.48391401, ...,  1.02268417,
         0.11825591,  0.70414811],
       [-0.72870798, -0.41311151, -0.03541401, ..., -0.44343132,
        -0.49609478, -0.53368022],
       ...,
       [ 0.57551824,  2.72122589,  0.42031986, ...,  2.5334037 ,
         0.70027235,  2.36421553],
       [ 0.09561194,  0.54966461,  0.36968276, ...,  0.14611777,
         0.11825591,  0.4169803 ],
       [-0.99270015, -0.64064456, -0.22349465, ..., -0.5927579 ,
        -0.43142629, -0.88692937]])

In [282]:
#X_test

array([[-0.25492071, -0.71935733, -0.33923659, ..., -0.32125503,
        -0.3667578 , -0.47850113],
       [-0.49880751,  0.15635386, -0.60688981, ...,  0.20623626,
         0.24759289,  0.05497315],
       [ 0.1760334 , -0.44955729, -0.24519627, ..., -0.41628103,
        -0.3020893 , -0.04473622],
       ...,
       [-0.44985532, -0.34604114, -0.57795433, ..., -0.52682149,
        -0.23742081, -0.59494204],
       [-1.33798792, -1.19644276, -0.68646239, ..., -1.29284744,
        -0.52842903, -1.39110032],
       [ 1.30455622,  0.94601251,  0.55052953, ...,  0.60185472,
         0.1829244 ,  0.72185723]])

In [350]:
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from math import sqrt
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.model_selection import GridSearchCV
from sklearn.datasets import load_iris
import warnings
warnings.filterwarnings("ignore")
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn.model_selection import KFold


#Implementing KNN with 5 nearest neighbors on valid set
knn5 = Pipeline([
        ('clf5', KNeighborsClassifier(n_neighbors=5))])
knn5 = knn5.fit(X_train, y_train)
y_pred = knn5.predict(X_test)
print()
print('KNN with 5 Nearest neighbor result on validation set:')
accuracy = accuracy_score(y_test, y_pred)*100
print('Accuracy of our model with 5 neighbours is equal to ' + str(round(accuracy, 2)) + ' %.')

#Classification reports and confusion matrices for test set
from sklearn.metrics import classification_report, confusion_matrix
print()
print('-----------------------------------')
print(confusion_matrix(y_test, y_pred))
print()


print()





KNN with 5 Nearest neighbor result on validation set:
Accuracy of our model with 5 neighbours is equal to 79.92 %.

-----------------------------------
[[  0   0   0   0   0   1   0   0   0]
 [  0   0   0   0   0   1   0   0   0]
 [  0   0  16   0   0  23   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   6   0   0 182   0   1   0]
 [  0   0   0   0   0   5   0   0   0]
 [  0   0   0   0   0   7   0   0   0]
 [  0   0   0   0   0   2   0   0   1]]




In [5]:
pip install imblearn

Note: you may need to restart the kernel to use updated packages.


In [352]:
from imblearn.over_sampling import SMOTE, ADASYN, RandomOverSampler, BorderlineSMOTE
from imblearn.under_sampling import RandomUnderSampler

from collections import Counter
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.dummy import DummyClassifier

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
#y = label_encoder.fit_transform(target_label)

dataset.shape
from sklearn.model_selection import RepeatedStratifiedKFold
# summarize the class distribution
target = obj_dataset['genre_label']
counter = Counter(target)
for k,v in counter.items():
    per = v / len(target) * 100
    print('Class=%d, Count=%d, Percentage=%.3f%%' % (k, v, per))
    
obj_dataset.head()

# evaluate a model
def evaluate_model(X_train, y_train, model):
    # define evaluation procedure
    cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=3, random_state=1)
    # evaluate model
    scores = cross_val_score(model, X_train, y_train, scoring='accuracy', cv=cv, n_jobs=-1)
    return scores

# define the reference model
model = DummyClassifier(strategy='most_frequent')
scores = evaluate_model(X_train, y_train, model)

# summarize performance
print('Mean Accuracy: %.3f (%.3f)' % (mean(scores), std(scores)))



Class=2, Count=111, Percentage=11.145%
Class=5, Count=794, Percentage=79.719%
Class=8, Count=18, Percentage=1.807%
Class=3, Count=6, Percentage=0.602%
Class=1, Count=5, Percentage=0.502%
Class=6, Count=18, Percentage=1.807%
Class=7, Count=36, Percentage=3.614%
Class=0, Count=2, Percentage=0.201%
Class=4, Count=6, Percentage=0.602%


NameError: name 'mean' is not defined

In [65]:
pip install keras

    100% |████████████████████████████████| 174kB 2.1MB/s 
Note: you may need to restart the kernel to use updated packages.


In [67]:
pip install tensorflow

    100% |████████████████████████████████| 175.3MB 320kB/s 
    100% |████████████████████████████████| 3.0MB 1.6MB/s 
    100% |████████████████████████████████| 51kB 3.5MB/s 
    100% |████████████████████████████████| 1.3MB 3.0MB/s 
    100% |████████████████████████████████| 460kB 3.2MB/s 
    100% |████████████████████████████████| 3.0MB 2.5MB/s 
  Using cached https://files.pythonhosted.org/packages/85/7a/ae480be23b768910a9327c33517ced4623ba88dc035f9ce0206657c353a9/scipy-1.4.1-cp37-cp37m-macosx_10_6_intel.whl
    100% |████████████████████████████████| 61kB 3.4MB/s 
    100% |████████████████████████████████| 112kB 2.8MB/s 
    100% |████████████████████████████████| 71kB 3.4MB/s 
    100% |████████████████████████████████| 2.8MB 3.1MB/s 
    100% |████████████████████████████████| 583kB 3.4MB/s 
    100% |████████████████████████████████| 92kB 3.1MB/s 
    100% |████████████████████████████████| 92kB 3.1MB/s 
    100% |████████████████████████████████| 778kB 3.2MB/s 
    100% |

In [360]:
import keras

class_weight = {0: 0.22,
                1: 0.10,
                2: 0.10,
                3: 0.10,
                4: 0.18,
                5: 0.01,
                6: 0.10,
                7: 0.10,
                8: 0.10 }
 

In [361]:
import keras
from keras import backend as K
import tensorflow as tf
from tensorflow.keras import layers

# Define our custom loss function
def focal_loss(y_train, y_pred):
    gamma = 2.0
    alpha = 0.25
    pt_1 = tf.where(tf.equal(y_train, 1), y_pred, tf.ones_like(y_pred))
    pt_0 = tf.where(tf.equal(y_train, 0), y_pred, tf.zeros_like(y_pred))
    return -K.sum(alpha * K.pow(1. - pt_1, gamma) * K.log(pt_1))-K.sum((1-alpha) * K.pow( pt_0, gamma) * K.log(1. - pt_0))

model = keras.Sequential()
model.add(layers.Dense(20, kernel_initializer='uniform', input_shape=(15,)))
model.add(layers.Dense(15, kernel_initializer='uniform', activation = 'relu'))
model.add(layers.Dense(13, kernel_initializer='uniform', activation = 'relu'))
model.add(layers.Dense(11, kernel_initializer='uniform', activation = 'relu'))
model.add(layers.Dense(9, kernel_initializer='uniform'))
model.add(layers.Activation('softmax'))

#cce = tf.keras.losses.CategoricalCrossentropy(y_train,y_pred)

# Compile our model
#adam = Adam(lr=0.0001)
adam = keras.optimizers.Adam(learning_rate=0.01)
model.compile(loss='sparse_categorical_crossentropy', metrics=["accuracy"], optimizer=adam)

In [362]:
print(X_train)
model.fit(X_train, y_train, epochs=10, batch_size=32, class_weight=class_weight)

[[ 3.12802531  1.94396893  1.3534892  ...  1.38533443  0.34459564
   1.97659814]
 [ 0.33949875  0.28922912 -0.48391401 ...  1.02268417  0.11825591
   0.70414811]
 [-0.72870798 -0.41311151 -0.03541401 ... -0.44343132 -0.49609478
  -0.53368022]
 ...
 [ 0.57551824  2.72122589  0.42031986 ...  2.5334037   0.70027235
   2.36421553]
 [ 0.09561194  0.54966461  0.36968276 ...  0.14611777  0.11825591
   0.4169803 ]
 [-0.99270015 -0.64064456 -0.22349465 ... -0.5927579  -0.43142629
  -0.88692937]]
Epoch 1/10
24/24 [==============================] - 0s 1ms/step - loss: 0.0567 - accuracy: 0.7470
Epoch 2/10
24/24 [==============================] - 0s 2ms/step - loss: 0.0469 - accuracy: 0.2918
Epoch 3/10
24/24 [==============================] - 0s 1ms/step - loss: 0.0456 - accuracy: 0.1058
Epoch 4/10
24/24 [==============================] - 0s 1ms/step - loss: 0.0448 - accuracy: 0.3641
Epoch 5/10
24/24 [==============================] - 0s 1ms/step - loss: 0.0440 - accuracy: 0.5609
Epoch 6/10
24/24 [

In [363]:
#print(X_train)
model.fit(X_train, y_train, epochs=30, batch_size=64, class_weight=class_weight)
y_pred = model.predict(X_test)
print(y_pred.shape)
print(np.unique(y_pred))

Epoch 1/30
12/12 [==============================] - 0s 2ms/step - loss: 0.0404 - accuracy: 0.6787
Epoch 2/30
12/12 [==============================] - 0s 2ms/step - loss: 0.0405 - accuracy: 0.7108
Epoch 3/30
12/12 [==============================] - 0s 2ms/step - loss: 0.0401 - accuracy: 0.6894
Epoch 4/30
12/12 [==============================] - 0s 2ms/step - loss: 0.0400 - accuracy: 0.6827
Epoch 5/30
12/12 [==============================] - 0s 1ms/step - loss: 0.0396 - accuracy: 0.6881
Epoch 6/30
12/12 [==============================] - 0s 1ms/step - loss: 0.0394 - accuracy: 0.7068
Epoch 7/30
12/12 [==============================] - 0s 2ms/step - loss: 0.0397 - accuracy: 0.6801
Epoch 8/30
12/12 [==============================] - 0s 1ms/step - loss: 0.0395 - accuracy: 0.7095
Epoch 9/30
12/12 [==============================] - 0s 2ms/step - loss: 0.0391 - accuracy: 0.7028
Epoch 10/30
12/12 [==============================] - 0s 2ms/step - loss: 0.0390 - accuracy: 0.6921
Epoch 11/30
12/12 [

In [368]:
#Classification reports and confusion matrices for test set
from sklearn.metrics import classification_report, confusion_matrix
print()
print('-----------------------------------')
#print(confusion_matrix(y_test, y_pred))
print()
#Confution Matrix and Classification Report
#Y_pred = model.predict_generator(validation_generator, num_of_test_samples // batch_size+1)
Y_pred = np.argmax(y_pred, axis=1)
print(Y_pred)
print('Confusion Matrix')
c_m = confusion_matrix(y_test,Y_pred)
print(c_m)
#print(confusion_matrix(validation_generator.classes, y_pred))
#print('Classification Report')
#target_names = ['Cats', 'Dogs', 'Horse']
#print(classification_report(validation_generator.classes, y_pred, target_names=target_names))

#print(matrix)



-----------------------------------

[5 2 2 2 2 2 2 2 2 5 2 5 5 2 5 5 6 5 2 5 2 5 2 2 2 2 5 5 2 5 2 5 5 2 7 2 5
 5 5 2 7 5 2 2 2 5 5 2 6 5 2 7 5 2 5 2 2 5 7 2 2 5 2 5 5 2 2 2 2 5 2 5 5 2
 5 2 2 2 5 2 2 2 2 2 5 5 2 2 2 7 2 2 5 2 5 2 2 2 2 5 2 2 2 2 2 2 5 5 5 2 5
 2 5 2 2 6 5 2 2 2 6 5 5 6 5 5 2 2 5 2 2 2 5 2 2 2 2 7 2 2 5 5 2 5 2 2 2 5
 2 5 5 2 5 5 2 7 5 2 2 5 2 2 2 5 5 2 2 2 2 5 2 2 5 6 2 5 5 2 2 2 5 5 2 2 2
 5 2 2 2 2 2 5 2 7 6 2 5 2 5 2 2 5 2 2 7 5 2 6 5 7 5 5 5 5 7 2 5 2 5 5 5 5
 2 2 2 2 2 5 2 5 5 2 5 2 5 5 2 5 2 5 5 5 2 5 2 5 5 5 2]
Confusion Matrix
[[ 0  0  0  0  0  0  1  0  0]
 [ 0  0  1  0  0  0  0  0  0]
 [ 0  0 37  0  0  2  0  0  0]
 [ 0  0  1  0  0  1  0  0  0]
 [ 0  0  1  0  0  1  0  0  0]
 [ 0  0 85  0  0 88  6 10  0]
 [ 0  0  0  0  0  4  1  0  0]
 [ 0  0  5  0  0  1  0  1  0]
 [ 0  0  3  0  0  0  0  0  0]]
